# Generated by Django 5.2.6 on 2025-09-28 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_pagos', '0002_alter_reserva_fecha_reserva_alter_reserva_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
