# Generated by Django 5.2.6 on 2025-09-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_pagos', '0003_alter_factura_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
