# Generated by Django 5.2.6 on 2025-09-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_pagos', '0004_alter_factura_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
