# Generated by Django 5.2.6 on 2025-09-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_pagos', '0005_alter_detallefactura_monto'),
        ('residentes', '0002_residente_foto_perfil_visitante_foto_referencial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fecha_pago',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='payment_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='residente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='residentes.residente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20),
        ),
    ]
