# Generated by Django 5.2.6 on 2025-09-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_usuario_bloqueado_hasta_usuario_intentos_fallidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_push', models.DateTimeField(auto_now_add=True)),
                ('hora_push', models.TimeField(auto_now_add=True)),
                ('urgente', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'db_table': 'aviso',
                'ordering': ['-fecha_push'],
            },
        ),
    ]
