# Generated by Django 5.2.6 on 2025-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], max_length=20),
        ),
    ]
