# Generated by Django 5.2.6 on 2025-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_aviso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='fecha_push',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='hora_push',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
