# Generated by Django 5.2.6 on 2025-09-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('APARTAMENTO', 'Apartamento'), ('CASA', 'Casa')], max_length=50)),
                ('num_habitaciones', models.IntegerField(default=1)),
                ('num_residentes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=150)),
                ('dni', models.CharField(max_length=30, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('tipo', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('INQUILINO', 'Inquilino'), ('FAMILIAR_PROPIETARIO', 'Familiar Propietario'), ('FAMILIAR_INQUILINO', 'Familiar Inquilino'), ('OTRO', 'Otro')], max_length=25)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('residencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='residentes.residencia')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='residentes.residente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('matricula', models.CharField(blank=True, max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('tipo', models.CharField(choices=[('COCHE', 'Coche'), ('MOTO', 'Moto'), ('BICICLETA', 'Bicicleta'), ('OTRO', 'Otro')], max_length=20)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='residentes.residente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='residentes.residente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
