# Generated by Django 5.2.6 on 2025-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residente',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitante',
            name='foto_referencial',
            field=models.URLField(blank=True, null=True),
        ),
    ]
