# Generated by Django 5.2.6 on 2025-09-25 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       # ('residentes', '0002_vehiculo_imagen_vehiculo_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_accesos', models.IntegerField(default=0)),
                ('accesos_autorizados', models.IntegerField(default=0)),
                ('visitantes_registrados', models.IntegerField(default=0)),
                ('vehiculos_ingresados', models.IntegerField(default=0)),
                ('anomalias_detectadas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAnomalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anomalia', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('datos_evento', models.JSONField()),
                ('nivel_severidad', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionMorosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad_morosidad', models.FloatField()),
                ('nivel_riesgo', models.CharField(max_length=10)),
                ('factores_riesgo', models.JSONField()),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
            ],
        ),
    ]
