# Generated by Django 5.2.6 on 2025-09-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_residente_foto_perfil_visitante_foto_referencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('foto_ruta', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('coincidencia', models.FloatField(blank=True, null=True)),
                ('residente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
            ],
        ),
    ]
