# Generated by Django 5.2.6 on 2025-09-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_residente_foto_perfil_visitante_foto_referencial'),
        ('vision_artificial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logreconocimiento',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residentes.residente'),
        ),
    ]
