# Generated by Django 5.2.6 on 2025-09-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_residente_foto_perfil_visitante_foto_referencial'),
        ('vision_artificial', '0002_alter_logreconocimiento_residente'),
    ]

    operations = [
        migrations.CreateModel(
            name='logReconocimientoPlaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('foto_ruta', models.URLField(blank=True, null=True)),
                ('placa_detectada', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residentes.vehiculo')),
            ],
        ),
    ]
