# Generated by Django 5.2.6 on 2025-09-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='estado',
        ),
    ]
