# Generated by Django 5.2.6 on 2025-09-25 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentes', '0002_vehiculo_imagen_vehiculo_vehiculo_placa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAccesoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=20)),
                ('confianza', models.FloatField()),
                ('imagen_acceso', models.ImageField(upload_to='accesos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('residente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='residentes.residente')),
            ],
        ),
        migrations.CreateModel(
            name='RostroResidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_encoding', models.JSONField()),
                ('imagen_referencia', models.ImageField(upload_to='rostros/')),
                ('calidad_imagen', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('residente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residentes.residente')),
            ],
        ),
    ]
