# Generated by Django 5.2.6 on 2025-09-22 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='costo_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En Mantenimiento'), ('cerrado', 'Cerrado')], default='disponible', max_length=50),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='requiere_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tiempo_reserva_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='En minutos', null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tiempo_reserva_minima',
            field=models.PositiveIntegerField(blank=True, help_text='En minutos', null=True),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regla',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='areas.areacomun')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_apertura'],
                'unique_together': {('area', 'dia_semana')},
            },
        ),
    ]
